name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test: # ジョブ名を変更
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8 # pnpmのバージョンを固定

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build projects
        run: pnpm -w build

      - name: Run Lighthouse CI
        uses: lhci/action@v4
        with:
          # lighthouserc.js があるので、基本的な設定は不要
          # action が pnpm install を再度実行しようとするのを防ぐ
          # budgetPath: ./lighthouserc.js # 設定ファイルのパスを明示的に指定することも可能
          # command: 'autorun' # デフォルトは autorun
          uploadArtifacts: true # アーティファクトとして結果を保存
          temporaryPublicStorage: true # 一時ストレージにアップロードしてレポートを見れるようにする
