name: Deploy (prebuilt)
on:
  push:
    branches: [ main ]

jobs:
  vercel-prebuilt:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 10.14.0 }
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: pnpm install --frozen-lockfile
      - run: npx vercel env pull .env.local --token ${{ secrets.VERCEL_TOKEN }}
      - run: npx vercel build --prod --token ${{ secrets.VERCEL_TOKEN }}
      - run: npx vercel deploy --prebuilt --prod --token ${{ secrets.VERCEL_TOKEN }}
