name: Deploy (Vercel prebuilt)
on:
  push:
    branches: [ main ]

jobs:
  vercel-prebuilt:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack (pnpm)
        run: |
          corepack enable
          corepack prepare pnpm@10.14.0 --activate

      - name: Install workspace deps (frozen)
        run: pnpm -w install --frozen-lockfile

      - name: Pull Vercel env to web/.env.local
        working-directory: web
        run: npx vercel env pull .env.local --environment=production --token "$VERCEL_TOKEN"

      - name: Build with Vercel CLI (prebuild at repo root)
        run: npx vercel build --prod --token "$VERCEL_TOKEN"

      - name: Deploy prebuilt to Vercel (prod)
        run: npx vercel deploy --prebuilt --prod --token "$VERCEL_TOKEN"
