name: Web Lighthouse (Local)

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lhci:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.14.0

      - name: Install deps (frozen lockfile)
        run: pnpm install --frozen-lockfile

      - name: Build web (offline)
        env:
          OFFLINE_BUILD: "1"
          NEXT_PUBLIC_SITE_URL: "http://localhost:3000"
        run: pnpm --filter web build

      # Do not start the server here; LHCI will start it using lighthouserc.js startServerCommand

      - name: Run Lighthouse CI (local)
        env:
          NEXT_PUBLIC_LHCI: "1"
        run: |
          set -e
          npx @lhci/cli@0.13.x autorun \
            --collect.url=http://localhost:3000/blog \
            --collect.url=http://localhost:3000/blog/sample-ci \
            --collect.numberOfRuns=3 \
            --upload.target=temporary-public-storage \
            --assert.assertions.performance=off \
            | tee lhci.log
          echo "### Lighthouse Reports" >> $GITHUB_STEP_SUMMARY
          echo "- Main listing (/blog)" >> $GITHUB_STEP_SUMMARY
          grep -F "Open the report at " lhci.log | head -n 1 | sed 's/.*Open the report at /  - /' >> $GITHUB_STEP_SUMMARY || true
          echo "- Sample page (/blog/sample-ci)" >> $GITHUB_STEP_SUMMARY
          grep -F "Open the report at " lhci.log | tail -n 1 | sed 's/.*Open the report at /  - /' >> $GITHUB_STEP_SUMMARY || true
